replicaCount: 1

image:
  repository: ikulyk404/todoapp
  tag: "4.0.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack
  interval: 10s
  path: /metrics
  port: http

resources: {}
